# 🐍 Crear Base de Datos de Actividades Infantiles
Este notebook crea todas las tablas necesarias para una base de datos PostgreSQL orientada a actividades para niños en Madrid.

In [ ]:


# Lista de queries para crear todas las tablas
queries = [
    '''
    CREATE TABLE IF NOT EXISTS categorias (
        id_categoria SERIAL PRIMARY KEY,
        nombre_categoria VARCHAR(100) NOT NULL
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS discapacidades (
        id_discapacidad SERIAL PRIMARY KEY,
        tipo VARCHAR(100) NOT NULL
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS modalidades (
        id_modalidad SERIAL PRIMARY KEY,
        descripcion VARCHAR(100) NOT NULL
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS ubicaciones (
        id_ubicacion SERIAL PRIMARY KEY,
        nombre_lugar VARCHAR(255) NOT NULL,
        direccion TEXT,
        codigo_postal VARCHAR(20),
        distrito VARCHAR(100),
        latitud DECIMAL(9, 6),
        longitud DECIMAL(9, 6)
    );
    ''',
    '''
    CREATE TABLE IF NOT EXISTS actividades (
        id_evento SERIAL PRIMARY KEY,
        nombre_evento VARCHAR(255) NOT NULL,
        id_categoria INT NOT NULL,
        id_discapacidad INT,
        fecha DATE,
        id_ubicacion INT,
        costo DECIMAL(10, 2),
        edad_min INT,
        edad_max INT,
        min_integrantes INT,
        max_integrantes INT,
        id_modalidad INT,
        descripcion TEXT,
        activo BOOLEAN DEFAULT TRUE,
        origen_web TEXT,
        ultimo_scrape TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria),
        FOREIGN KEY (id_discapacidad) REFERENCES discapacidades(id_discapacidad),
        FOREIGN KEY (id_ubicacion) REFERENCES ubicaciones(id_ubicacion),
        FOREIGN KEY (id_modalidad) REFERENCES modalidades(id_modalidad)
    );
    '''
]

for query in queries:
    cur.execute(query)

conn.commit()
cur.close()
conn.close()
print("✅ Tablas creadas exitosamente.")

In [ ]:
import pandas as pd

# Crear los datos de ejemplo
data = [
    [1, "Pintura Creativa", "Talleres", "Ninguna", "2025-05-10", "Centro Cultural La Estación", 5, "6-12", 5, "Interior"],
    [2, "Yoga para peques", "Salud", "Visual", "2025-05-12", "Parque Central", 0, "4-10", 3, "Al aire libre"],
    [3, "Fútbol Inclusivo", "Deportes", "Motora", "2025-05-15", "Cancha Municipal", 2, "6-14", 10, "Al aire libre"],
    [4, "Cuentacuentos", "Cultura", "Auditiva", "2025-05-11", "Biblioteca Pública", 0, "3-8", 2, "Interior"],
    [5, "Cocina en Familia", "Talleres", "Ninguna", "2025-05-14", "Centro Comunitario Norte", 8, "5-12", 4, "Interior"]
]

# Nombres de las columnas
columns = [
    "id_evento", "nombre_evento", "categoria", "discapacidad", "fecha",
    "ubicacion", "costo", "edad_dirigida", "min_integrantes", "modalidad"
]

# Crear el DataFrame
df = pd.DataFrame(data, columns=columns)

# Guardar como archivo CSV
csv_path = "/mnt/data/actividades_ninos.csv"
df.to_csv(csv_path, index=False)

csv_path

,id_evento,nombre_evento,categoria,discapacidad,fecha,ubicacion,costo,edad_dirigida,min_integrantes,modalidad
0,1,Pintura Creativa,Talleres,Ninguna,2025-05-10,Centro Cultural La Estación,5,6-12,5,Interior
1,2,Yoga para peques,Salud,Visual,2025-05-12,Parque Central,0,4-10,3,Al aire libre
2,3,Fútbol Inclusivo,Deportes,Motora,2025-05-15,Cancha Municipal,2,6-14,10,Al aire libre
3,4,Cuentacuentos,Cultura,Auditiva,2025-05-11,Biblioteca Pública,0,3-8,2,Interior
4,5,Cocina en Familia,Talleres,Ninguna,2025-05-14,Centro Comunitario Norte,8,5-12,4,Interior

In [3]:
# Añadir una columna extra 'descripcion' para detallar la actividad
# Crear más eventos de ejemplo
data_extended = [
    [1, "Pintura Creativa", "Talleres", "Ninguna", "2025-05-10", "Centro Cultural La Estación", 5, "6-12", 5, "Interior", "Taller de pintura para estimular la creatividad de los niños."],
    [2, "Yoga para peques", "Salud", "Visual", "2025-05-12", "Parque Central", 0, "4-10", 3, "Al aire libre", "Sesión de yoga enfocada en el bienestar físico y mental de los niños con discapacidad visual."],
    [3, "Fútbol Inclusivo", "Deportes", "Motora", "2025-05-15", "Cancha Municipal", 2, "6-14", 10, "Al aire libre", "Partido de fútbol donde los niños con discapacidad motora participan junto a otros niños."],
    [4, "Cuentacuentos", "Cultura", "Auditiva", "2025-05-11", "Biblioteca Pública", 0, "3-8", 2, "Interior", "Sesión de cuentos con enfoque en la inclusión de niños con dificultades auditivas."],
    [5, "Cocina en Familia", "Talleres", "Ninguna", "2025-05-14", "Centro Comunitario Norte", 8, "5-12", 4, "Interior", "Taller de cocina donde los niños aprenden a hacer recetas fáciles y divertidas junto con sus padres."],
    [6, "Cine Familiar", "Cultura", "Ninguna", "2025-06-01", "Cine Municipal", 3, "6-14", 5, "Interior", "Proyección de una película infantil para toda la familia, con actividades previas para niños."],
    [7, "Natación para niños", "Salud", "Ninguna", "2025-06-10", "Piscina Municipal", 10, "5-12", 4, "Al aire libre", "Clase de natación para niños, enfocada en la mejora de habilidades acuáticas."],
    [8, "Taller de Ciencia", "Talleres", "Ninguna", "2025-06-15", "Museo de Ciencias", 7, "8-15", 6, "Interior", "Taller práctico de experimentos científicos para despertar el interés por la ciencia."],
    [9, "Carrera Infantil", "Deportes", "Ninguna", "2025-06-20", "Parque Deportivo", 5, "6-12", 10, "Al aire libre", "Competencia de carreras con premios para los niños que participen."],
    [10, "Teatro Infantil", "Cultura", "Auditiva", "2025-06-25", "Teatro Municipal", 0, "3-10", 4, "Interior", "Espectáculo de teatro con una obra inclusiva para niños con discapacidad auditiva."]
]

# Nuevas columnas con los datos extendidos
columns_extended = [
    "id_evento", "nombre_evento", "categoria", "discapacidad", "fecha",
    "ubicacion", "costo", "edad_dirigida", "min_integrantes", "modalidad", "descripcion"
]

# Crear el DataFrame extendido
df_extended = pd.DataFrame(data_extended, columns=columns_extended)

# Guardar como archivo CSV
csv_path_extended = "actividades_ninos_extended.csv"
df_extended.to_csv(csv_path_extended, index=False)

csv_path_extended

'actividades_ninos_extended.csv'

In [5]:
# Añadir la columna 'link' para cada evento, con enlaces ficticios
data_with_link = [
    [1, "Pintura Creativa", "Talleres", "Ninguna", "2025-05-10", "Centro Cultural La Estación", 5, "6-12", 5, "Interior", "Taller de pintura para estimular la creatividad de los niños.", "https://www.ejemplo.com/entradas/pintura_creativa"],
    [2, "Yoga para peques", "Salud", "Visual", "2025-05-12", "Parque Central", 0, "4-10", 3, "Al aire libre", "Sesión de yoga enfocada en el bienestar físico y mental de los niños con discapacidad visual.", "https://www.ejemplo.com/entradas/yoga_peques"],
    [3, "Fútbol Inclusivo", "Deportes", "Motora", "2025-05-15", "Cancha Municipal", 2, "6-14", 10, "Al aire libre", "Partido de fútbol donde los niños con discapacidad motora participan junto a otros niños.", "https://www.ejemplo.com/entradas/futbol_inclusivo"],
    [4, "Cuentacuentos", "Cultura", "Auditiva", "2025-05-11", "Biblioteca Pública", 0, "3-8", 2, "Interior", "Sesión de cuentos con enfoque en la inclusión de niños con dificultades auditivas.", "https://www.ejemplo.com/entradas/cuentacuentos"],
    [5, "Cocina en Familia", "Talleres", "Ninguna", "2025-05-14", "Centro Comunitario Norte", 8, "5-12", 4, "Interior", "Taller de cocina donde los niños aprenden a hacer recetas fáciles y divertidas junto con sus padres.", "https://www.ejemplo.com/entradas/cocina_familia"],
    [6, "Cine Familiar", "Cultura", "Ninguna", "2025-06-01", "Cine Municipal", 3, "6-14", 5, "Interior", "Proyección de una película infantil para toda la familia, con actividades previas para niños.", "https://www.ejemplo.com/entradas/cine_familiar"],
    [7, "Natación para niños", "Salud", "Ninguna", "2025-06-10", "Piscina Municipal", 10, "5-12", 4, "Al aire libre", "Clase de natación para niños, enfocada en la mejora de habilidades acuáticas.", "https://www.ejemplo.com/entradas/natacion_ninos"],
    [8, "Taller de Ciencia", "Talleres", "Ninguna", "2025-06-15", "Museo de Ciencias", 7, "8-15", 6, "Interior", "Taller práctico de experimentos científicos para despertar el interés por la ciencia.", "https://www.ejemplo.com/entradas/taller_ciencia"],
    [9, "Carrera Infantil", "Deportes", "Ninguna", "2025-06-20", "Parque Deportivo", 5, "6-12", 10, "Al aire libre", "Competencia de carreras con premios para los niños que participen.", "https://www.ejemplo.com/entradas/carrera_infantil"],
    [10, "Teatro Infantil", "Cultura", "Auditiva", "2025-06-25", "Teatro Municipal", 0, "3-10", 4, "Interior", "Espectáculo de teatro con una obra inclusiva para niños con discapacidad auditiva.", "https://www.ejemplo.com/entradas/teatro_infantil"]
]

# Crear el DataFrame con la nueva columna
columns_with_link = [
    "id_evento", "nombre_evento", "categoria", "discapacidad", "fecha",
    "ubicacion", "costo", "edad_dirigida", "min_integrantes", "modalidad", "descripcion", "link"
]

# Crear el DataFrame final
df_with_link = pd.DataFrame(data_with_link, columns=columns_with_link)

# Guardar como archivo CSV
csv_path_with_link = "actividades_ninos_with_link.csv"
df_with_link.to_csv(csv_path_with_link, index=False)

csv_path_with_link

'actividades_ninos_with_link.csv'

In [6]:
df_with_link.head()

,id_evento,nombre_evento,categoria,discapacidad,fecha,ubicacion,costo,edad_dirigida,min_integrantes,modalidad,descripcion,link
0,1,Pintura Creativa,Talleres,Ninguna,2025-05-10,Centro Cultural La Estación,5,6-12,5,Interior,Taller de pintura para estimular la creativida...,https://www.ejemplo.com/entradas/pintura_creativa
1,2,Yoga para peques,Salud,Visual,2025-05-12,Parque Central,0,4-10,3,Al aire libre,Sesión de yoga enfocada en el bienestar físico...,https://www.ejemplo.com/entradas/yoga_peques
2,3,Fútbol Inclusivo,Deportes,Motora,2025-05-15,Cancha Municipal,2,6-14,10,Al aire libre,Partido de fútbol donde los niños con discapac...,https://www.ejemplo.com/entradas/futbol_inclusivo
3,4,Cuentacuentos,Cultura,Auditiva,2025-05-11,Biblioteca Pública,0,3-8,2,Interior,Sesión de cuentos con enfoque en la inclusión ...,https://www.ejemplo.com/entradas/cuentacuentos
4,5,Cocina en Familia,Talleres,Ninguna,2025-05-14,Centro Comunitario Norte,8,5-12,4,Interior,Taller de cocina donde los niños aprenden a ha...,https://www.ejemplo.com/entradas/cocina_familia

In [10]:
import pandas as pd

# Crear el DataFrame principal con columna discapacidad True/False
data_main = [
    [1, "Pintura Creativa", "Talleres", False, "2025-05-10", "Centro Cultural La Estación", 5, "6-12", 5, "Interior", "Taller de pintura para estimular la creatividad de los niños.", "https://www.ejemplo.com/entradas/pintura_creativa"],
    [2, "Yoga para peques", "Salud", True, "2025-05-12", "Parque Central", 0, "4-10", 3, "Al aire libre", "Sesión de yoga enfocada en el bienestar físico y mental de los niños con discapacidad visual.", "https://www.ejemplo.com/entradas/yoga_peques"],
    [3, "Fútbol Inclusivo", "Deportes", True, "2025-05-15", "Cancha Municipal", 2, "6-14", 10, "Al aire libre", "Partido de fútbol donde los niños con discapacidad motora participan junto a otros niños.", "https://www.ejemplo.com/entradas/futbol_inclusivo"],
    [4, "Cuentacuentos", "Cultura", True, "2025-05-11", "Biblioteca Pública", 0, "3-8", 2, "Interior", "Sesión de cuentos con enfoque en la inclusión de niños con dificultades auditivas.", "https://www.ejemplo.com/entradas/cuentacuentos"],
    [5, "Cocina en Familia", "Talleres", False, "2025-05-14", "Centro Comunitario Norte", 8, "5-12", 4, "Interior", "Taller de cocina donde los niños aprenden a hacer recetas fáciles y divertidas junto con sus padres.", "https://www.ejemplo.com/entradas/cocina_familia"],
    [6, "Cine Familiar", "Cultura", False, "2025-06-01", "Cine Municipal", 3, "6-14", 5, "Interior", "Proyección de una película infantil para toda la familia, con actividades previas para niños.", "https://www.ejemplo.com/entradas/cine_familiar"],
    [7, "Natación para niños", "Salud", False, "2025-06-10", "Piscina Municipal", 10, "5-12", 4, "Al aire libre", "Clase de natación para niños, enfocada en la mejora de habilidades acuáticas.", "https://www.ejemplo.com/entradas/natacion_ninos"],
    [8, "Taller de Ciencia", "Talleres", False, "2025-06-15", "Museo de Ciencias", 7, "8-15", 6, "Interior", "Taller práctico de experimentos científicos para despertar el interés por la ciencia.", "https://www.ejemplo.com/entradas/taller_ciencia"],
    [9, "Carrera Infantil", "Deportes", False, "2025-06-20", "Parque Deportivo", 5, "6-12", 10, "Al aire libre", "Competencia de carreras con premios para los niños que participen.", "https://www.ejemplo.com/entradas/carrera_infantil"],
    [10, "Teatro Infantil", "Cultura", True, "2025-06-25", "Teatro Municipal", 0, "3-10", 4, "Interior", "Espectáculo de teatro con una obra inclusiva para niños con discapacidad auditiva.", "https://www.ejemplo.com/entradas/teatro_infantil"]
]

# Crear el DataFrame principal
columns_main = [
    "id_evento", "nombre_evento", "categoria", "discapacidad", "fecha",
    "ubicacion", "costo", "edad_dirigida", "min_integrantes", "modalidad", "descripcion", "link"
]

df_main = pd.DataFrame(data_main, columns=columns_main)

# Lista de relaciones entre eventos y discapacidades
data_disabilities = [
    [2, "Visual"],
    [3, "Motora"],
    [4, "Auditiva"],
    [10, "Auditiva"]
]

# Columnas correspondientes
columns_disabilities = ["id_evento", "discapacidad"]

# Crear el DataFrame
df_disabilities = pd.DataFrame(data_disabilities, columns=columns_disabilities)


# Guardar ambos DataFrames como archivos CSV
csv_path_main = "actividades_ninos_main.csv"
df_main.to_csv(csv_path_main, index=False)

csv_path_disabilities = "tipos_discapacidades.csv"
df_disabilities.to_csv(csv_path_disabilities, index=False)

csv_path_main, csv_path_disabilities

('actividades_ninos_main.csv', 'tipos_discapacidades.csv')

In [11]:
df_disabilities.head()

   id_evento discapacidad
0          2       Visual
1          3       Motora
2          4     Auditiva
3         10     Auditiva

In [12]:
df_with_link.head()

,id_evento,nombre_evento,categoria,discapacidad,fecha,ubicacion,costo,edad_dirigida,min_integrantes,modalidad,descripcion,link
0,1,Pintura Creativa,Talleres,Ninguna,2025-05-10,Centro Cultural La Estación,5,6-12,5,Interior,Taller de pintura para estimular la creativida...,https://www.ejemplo.com/entradas/pintura_creativa
1,2,Yoga para peques,Salud,Visual,2025-05-12,Parque Central,0,4-10,3,Al aire libre,Sesión de yoga enfocada en el bienestar físico...,https://www.ejemplo.com/entradas/yoga_peques
2,3,Fútbol Inclusivo,Deportes,Motora,2025-05-15,Cancha Municipal,2,6-14,10,Al aire libre,Partido de fútbol donde los niños con discapac...,https://www.ejemplo.com/entradas/futbol_inclusivo
3,4,Cuentacuentos,Cultura,Auditiva,2025-05-11,Biblioteca Pública,0,3-8,2,Interior,Sesión de cuentos con enfoque en la inclusión ...,https://www.ejemplo.com/entradas/cuentacuentos
4,5,Cocina en Familia,Talleres,Ninguna,2025-05-14,Centro Comunitario Norte,8,5-12,4,Interior,Taller de cocina donde los niños aprenden a ha...,https://www.ejemplo.com/entradas/cocina_familia